app = "informativecourses"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true  # Enables stopping Machines when idle
  auto_start_machines = true # Keeps Machines starting on demand
  min_machines_running = 0   # Allows scaling to zero when idle
  processes = ["app"]

[[vm]]
  memory = "512mb"           # Increased to 512 MB (closest valid size to 524 MB)
  cpu_kind = "shared"
  cpus = 1

# [mounts] section removed since SQLite is no longer used (replaced by PostgreSQL)